### ISSUE TITLE
Add possibility to define custom autocomplete options

### ISSUE THREAD

**Issue by gturi** [gturi/nca#62]
```yml
aliases:
  - name: update
    description: merge specified branch into current one
    commandType: Function
    command: |
      const result = safeExec('git branch --show-current');

      const currentBranch = result.stdout;
      if (currentBranch === 'main' || currentBranch === 'master' || currentBranch === 'develop' ) {
        throw new Error(`${currentBranch} should be updated via PR`);
      }

      const branch = args.branch;
      const mergeStrategy = args.s;
      safeExec(`git checkout ${branch}`);
      safeExec(`git pull`);
      safeExec(`git checkout ${currentBranch}`);
      safeExec(`git merge ${mergeStrategy} ${branch}`);
    options:
      - name: s
        alternativeName: strategy
        description: merge strategy
        optionType: String
        defaultValue: ''
    positionalArguments:
      - name: branch
        description: branch to pull and merge into current one
        type: String
        required: true
```

It would be nice if there was the possibility to have custom autocompletion. I.E. branch param could be autocompleted by running `git branch` command and add the option to yargs default completion list.

Check https://github.com/yargs/yargs/issues/1013
